### ISSUE TITLE
Main config block

### ISSUE THREAD

**Issue by kennedyrose** [smarterlabs/omni#31]
No interpolate directive on configs

```yaml config
interpolate:
  _scope_: nav
otherSetting: true
```

instead of:

```yaml config interpolate
_scope_: nav
```

```yaml config
otherSetting: true
```
